language: rust
sudo: false
dist: trusty

# build website
script:
  - export PATH=$PATH:~/.cargo/bin
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      curl -sL https://github.com/cobalt-org/cobalt.rs/releases/download/v0.12.1/cobalt-v0.12.1-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C $HOME/.cargo/bin &&
      cobalt build &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -c "cljvm.github.io" -m "Update" -b master -r https://"$GITHUB_TOKEN"@github.com/cljvm/cljvm.github.io.git _site &&
      echo "Update"
    fi
